apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-project.io--serverless-allow-internal-http
  labels:
    kyma-project.io/module: serverless
    app.kubernetes.io/name: buildless-serverless
    app.kubernetes.io/instance: buildless-serverless-allow-internal-http
    app.kubernetes.io/version: {{ .Values.global.images.function_controller.version }}
    app.kubernetes.io/component: network-policy
    app.kubernetes.io/part-of: serverless
    purpose: internal-http
spec:
  podSelector:
    matchLabels:
      kyma-project.io/module: serverless
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 12137
