version: 2.1
executors:
  go-env:
    docker:
      - image: cimg/go:1.22
  ubuntu:
    machine:
      image: ubuntu-2004:202105-01
workflows:
  version: 2
  build:
    jobs:
      - lint
      - unit-tests
      - pre-integration
      #- post-integration
jobs:
  lint:
    executor: go-env
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
      - run:
          name: Run lint
          command: golangci-lint run components/operator/
  unit-tests:
    executor: go-env
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make -C components/operator test
  pre-integration:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update 
            sudo apt-get install -y curl bash make
            curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v4.4.8 bash
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            wget https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz
            sudo tar -xvf go1.22.1.linux-amd64.tar.gz -C /usr/local
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
      - run:
          name: Run Docker
          command: |
            sudo systemctl start docker
            sleep 10
            sudo docker run -d --privileged --name k3s-dind --network host -v /var/run/docker.sock:/var/run/docker.sock docker:dind
            sudo docker exec k3s-dind dockerd-entrypoint.sh &
            sleep 20
      - run:
          name: Create Kabernetes cluster
          command: |
            k3d cluster create k3dCluster --agents 1 --image "rancher/k3s:v1.29.3-k3s1" --port 80:80@loadbalancer --port 443:443@loadbalancer --wait
      - run:
          name: Run integration tests
          command: |
            make -C components/operator deploy
            make -C tests/operator test
          environment:
            IMG: europe-docker.pkg.dev/kyma-project/dev/serverless-operator:PR-963
#  post-integration:
#    executor: go-env
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Install k3d
#          command: |
#            curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v4.4.8 bash
#      - run:
#          name: Install kubectl
#          command: |
#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#            chmod +x kubectl
#            sudo mv kubectl /usr/local/bin/
#      - run:
#          name: Create k3d cluster
#          command: |
#            k3d cluster create k3dCluster --agents 1 --image rancher/k3s:v1.29.3-k3s1 --port 80:80@loadbalancer --port 443:443@loadbalancer
#      - run:
#          name: Waiting for node ready state
#          command: kubectl wait --for=condition=Ready node --all --timeout=60s
#      - run:
#          name: Run integration tests (pre)
#          command: |
#            make -C components/operator deploy
#            make -C tests/operator test
#          environment:
#            IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:ff0bbe7c9f0a14109758d7764c879ca89b9949c7