version: 2.1
executors:
  go-env:
    docker:
      - image: cimg/go:1.22
  docker-dind:
    machine:
      image: ubuntu-2204:2024.04.4
    resource_class: medium
  docker-executor:
    docker:
      - image: cimg/go:1.22.3
        environment:
          DOCKER_HOST: tcp://localhost:45815
      - image: docker:20.10.7-dind
        command: --privileged   #add this line
        environment:
          DOCKER_DRIVER: overlay2
workflows:
  version: 2
  build:
    jobs:
      #- lint
      #- unit-tests
      - pre-integration
      - gardener-integration-test
      #- post-integration
jobs:
#  lint: DONE
#    executor: go-env
#    steps:
#      - checkout
#      - run:
#          name: Install golangci-lint
#          command: |
#            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
#      - run:
#          name: Run lint
#          command: golangci-lint run components/operator/

#  unit-tests: DONE
#    executor: go-env
#    steps:
#      - checkout
#      - run:
#          name: Run unit tests
#          command: make -C components/operator test

  pre-integration:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Setup Environment
          command: |
            go version   #confirm go is installed
            sudo chmod a+r /var/run/docker.sock  #change permission
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: install k3d
          command: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      - run:
          name: create cluster
          command: |
            echo 'export KUBECONFIG=/etc/kubernetes/admin.conf' >> $HOME/.bashrc &&
            k3d cluster create kyma --agents 1 --image "rancher/k3s:v1.29.3-k3s1" --port 80:80@loadbalancer --port 443:443@loadbalancer --wait
      - run:
          name: run integration test (pre)
          command: |
            kubectl config view
            make -C components/operator deploy-local
            make -C tests/operator test
          environment:
            IMG: europe-docker.pkg.dev/kyma-project/dev/serverless-operator:PR-963

  gardener-integration-test:
    docker:
      - image: cimg/go:1.22.3
    steps:
      - checkout
      - run:
          name: Set up Go
          command: go version
      - run:
          name: Save SA
          command: 'echo "$GARDENER_SA" > /tmp/gardener-sa.yaml'
      - run:
          name: Provision Gardener
          command: make -C hack provision-gardener
          environment:
            GARDENER_SECRET_NAME: ${GARDENER_SECRET_NAME}
            GARDENER_PROJECT: ${GARDENER_PROJECT}
            GARDENER_SA_PATH: /tmp/gardener-sa.yaml
      - run:
          name: Run Test
          command: |
            echo ${GARDENER_SECRET_NAME} && echo ${GARDENER_PROJECT} &&
            make -C components/operator deploy && cat /tmp/gardener-sa.yaml &&
            make -C tests/operator test
          environment:
            IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${CIRCLE_SHA1}
      - run:
          name: Deprovision Gardener
          command: make -C hack deprovision-gardener
          environment:
            GARDENER_SA_PATH: /tmp/gardener-sa.yaml
#  post-integration:
#    executor: go-env
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Install k3d
#          command: |
#            curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v4.4.8 bash
#      - run:
#          name: Install kubectl
#          command: |
#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#            chmod +x kubectl
#            sudo mv kubectl /usr/local/bin/
#      - run:
#          name: Create k3d cluster
#          command: |
#            k3d cluster create k3dCluster --agents 1 --image rancher/k3s:v1.29.3-k3s1 --port 80:80@loadbalancer --port 443:443@loadbalancer
#      - run:
#          name: Waiting for node ready state
#          command: kubectl wait --for=condition=Ready node --all --timeout=60s
#      - run:
#          name: Run integration tests (pre)
#          command: |
#            make -C components/operator deploy
#            make -C tests/operator test
#          environment:
#            IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:ff0bbe7c9f0a14109758d7764c879ca89b9949c7