name: integration tests

on:
  workflow_call:
    inputs:
      image:
        description: 'The image to test'
        required: true
        type: string
      trigger_btp:
        description: 'Trigger BTP integration test'
        required: false
        type: boolean
        default: false

jobs:
  buildless-serverless-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make install-buildless-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: ${{ inputs.image }}
          INCLUDE_GITOPS_TEST: false
