name: pull

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  integrations:
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/serverless-operator@sha256:226e2f58e18bf85c10289bdcc1ad5151bc3383247b2b85d209170cc068c5fdf0
