name: push

on:
  push:
    branches: ["main", "release-*"]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  integrations:
    uses: ./.github/workflows/_integration-tests.yaml
