name: push

on:
  push:
    branches: ["main", "release-*"]

jobs:
  operator-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: "europe-docker.pkg.dev/kyma-project/prod/serverless-operator:aa4277f136720b7a1f57f0f033eb4d6d101d515b"
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info
