name: serverless operator build (push)

on:
  pull_request:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: compute-tag
        uses: ./.github/actions/compute-tag
      - uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
        with:
          name: serverless-operator/ga
          dockerfile: components/operator/Dockerfile
          context: .
          tags: ${{ steps.compute-tag.outputs.tag }}

  build-image:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: serverless-operator/ga
      dockerfile: components/operator/Dockerfile
      context: .
      tags: ${{ needs.compute-tag.outputs.tag }}
