name: serverless runtimes build (push)

on:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'

permissions:
  id-token: write
  contents: read

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.sha }}

  build-image-nodejs18:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs18/ga
      dockerfile: nodejs18/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-image-nodejs20:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs20/ga
      dockerfile: nodejs20/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-image-python39:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python39/ga
      dockerfile: python39/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-image-python312:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python312/ga
      dockerfile: python312/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tag.outputs.tag }}

  build-image-java17:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-java17-jvm-alpha/ga
      dockerfile: Dockerfile-jvm-runtime
      context: components/runtimes/java17
      tags: ${{ needs.compute-tag.outputs.tag }}
