name: Serverless verify

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  serverless-lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-libgit2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: 'components/serverless'

  serverless-unit-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-libgit2
      - name: run test
        run: make -C components/serverless test

  serverless-integration-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run integration test (pre)
        if: github.event_name == 'pull_request'
        run: |
          make install-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/serverless-operator:PR-${{ github.event.number }}
      - name: run integration test (post)
        if: github.event_name == 'push'
        run: |
          make install-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${{ github.sha }}

  git-auth-integration-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run git auth tests
        run: |
          make install-serverless-custom-operator
          make -C tests/serverless git-auth-integration
          make remove-serverless
        env:
          APP_TEST_GITHUB_SSH_AUTH_KEY: ${{ secrets.GIT_AUTH_TEST_GITHUB_SSH_KEY }}
          APP_TEST_AZURE_BASIC_AUTH_USERNAME: ${{ secrets.GIT_AUTH_TEST_AZURE_USERNAME }}
          APP_TEST_AZURE_BASIC_AUTH_PASSWORD: ${{ secrets.GIT_AUTH_TEST_AZURE_PASSWORD }}
          IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${{ github.sha }}

  serverless-upgrade-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: upgrade test
        run: |
          make install-serverless-latest-release install-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:${{ github.sha }}
