name: serverless operator build (push)

on:
  push:
    branches: [ "main", "release-*" ]

permissions:
  id-token: write
  contents: read

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.sha }}

  build-image:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: serverless-operator/ga
      dockerfile: components/operator/Dockerfile
      context: .
      tags: ${{ needs.compute-tag.outputs.tag }}
